#!/usr/bin/env python
# vim:fileencoding=utf-8

# you may want change this
dest_url = '{{ url }}'
import sys
from subprocess import call
args = []
for f in sys.argv[1:]:
  args.extend(['-F', 'name=@'+f])
cmd = ['curl', '--compressed', dest_url] + args
sys.exit(call(cmd))
